require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable

  Include:
    - "app/**/*"
    - "lib/**/*"
    - "*/.gemspec"
    - "Gemfile"
    - "spec/**/*"
  Exclude:
    - "vendor/**/*"
    - "bin/*"
    - "db/**/*"
    - "config/**/*"
    - "app/views/**/*"
    - "app/assets/**/*"
    - "app/javascript/**/*"
    - ".idea/**/*"
    - "**/.DS_Store"
    - "**/.keep"

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '*/.rake'
    - 'spec/**/*.rb'

RSpec/ContextWording:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false
